# Generated by Django 2.0.2 on 2022-10-31 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20221026_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('admin', models.CharField(max_length=32, verbose_name='管理员权限')),
                ('addr', models.CharField(max_length=64, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.BigIntegerField(verbose_name='手机号')),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 10, 52, 0, 799610, tzinfo=utc)),
        ),
    ]
