# Generated by Django 2.0.2 on 2022-11-01 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_auto_20221031_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 9, 2, 46, 223516, tzinfo=utc)),
        ),
    ]
