# Generated by Django 2.0.2 on 2022-11-05 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_auto_20221104_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='bbd_type',
            field=models.CharField(max_length=128, null=True, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bbd_url',
            field=models.CharField(max_length=128, null=True, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='capital_reserves',
            field=models.CharField(max_length=128, null=True, verbose_name='资本公积'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='cash_central_bank_funds',
            field=models.CharField(max_length=128, null=True, verbose_name='现金及存放中央银行款项(元)'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='company_name',
            field=models.CharField(max_length=128, null=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='fixed_assets',
            field=models.CharField(max_length=128, null=True, verbose_name='固定资产'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='interest_payable',
            field=models.CharField(max_length=128, null=True, verbose_name='应付利息(元)'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='paid_in_capital',
            field=models.CharField(max_length=128, null=True, verbose_name='实收资本'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='risk_preparation',
            field=models.CharField(max_length=128, null=True, verbose_name='一般风险准备(元)'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='sellable_assetset',
            field=models.CharField(max_length=128, null=True, verbose_name='可供出售金融资产(元)'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='total_assets',
            field=models.CharField(max_length=128, null=True, verbose_name='资产总计'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='type',
            field=models.CharField(max_length=128, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 1, 13, 29, 951837, tzinfo=utc)),
        ),
    ]
