# Generated by Django 2.0.2 on 2022-11-06 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_auto_20221106_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 3, 46, 18, 389303, tzinfo=utc)),
        ),
    ]
