# Generated by Django 2.0.2 on 2022-11-08 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0042_auto_20221106_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='delconinfo',
            name='loss_rate',
            field=models.CharField(max_length=128, null=True, verbose_name='缺失率'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 33, 28, 71772, tzinfo=utc)),
        ),
    ]
