# Generated by Django 2.0.2 on 2022-11-08 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0043_auto_20221108_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='delconinfo',
            name='loss_rate_status',
            field=models.CharField(max_length=128, null=True, verbose_name='计算状态'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 52, 3, 656350, tzinfo=utc)),
        ),
    ]
