# Generated by Django 2.0.2 on 2023-01-11 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0049_auto_20230111_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='admin',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 2, 56, 28, 409776, tzinfo=utc)),
        ),
    ]
