# Generated by Django 2.0.2 on 2023-01-17 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0053_auto_20230117_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='YhzxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhzx_id', models.CharField(max_length=128, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, null=True, verbose_name='公司名')),
                ('capital_adequacy_ratio', models.CharField(max_length=128, null=True, verbose_name='资本充足率(%)')),
                ('provision_coverage', models.CharField(max_length=128, null=True, verbose_name='拨备覆盖率(%)')),
                ('total_deposit', models.CharField(max_length=128, null=True, verbose_name='存款总额（%）')),
                ('total_loan', models.CharField(max_length=128, null=True, verbose_name='贷款总额（%）')),
                ('non_interest_income', models.CharField(max_length=128, null=True, verbose_name='非利息收入（元）')),
                ('net_interest_margin', models.CharField(max_length=128, null=True, verbose_name='净息差(%)')),
            ],
            options={
                'db_table': 'yhzxinfo',
            },
        ),
        migrations.CreateModel(
            name='YhzxInfoDelMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, null=True, verbose_name='公司名')),
                ('capital_adequacy_ratio', models.CharField(max_length=128, null=True, verbose_name='资本充足率(%)')),
                ('provision_coverage', models.CharField(max_length=128, null=True, verbose_name='拨备覆盖率(%)')),
                ('total_deposit', models.CharField(max_length=128, null=True, verbose_name='存款总额（%）')),
                ('total_loan', models.CharField(max_length=128, null=True, verbose_name='贷款总额（%）')),
                ('non_interest_income', models.CharField(max_length=128, null=True, verbose_name='非利息收入（元）')),
                ('net_interest_margin', models.CharField(max_length=128, null=True, verbose_name='净息差(%)')),
            ],
            options={
                'db_table': 'yhzxinfodelmark',
            },
        ),
        migrations.CreateModel(
            name='YhzxInfoFilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhzx_id', models.CharField(max_length=128, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, null=True, verbose_name='公司名')),
                ('capital_adequacy_ratio', models.CharField(max_length=128, null=True, verbose_name='资本充足率(%)')),
                ('provision_coverage', models.CharField(max_length=128, null=True, verbose_name='拨备覆盖率(%)')),
                ('total_deposit', models.CharField(max_length=128, null=True, verbose_name='存款总额（%）')),
                ('total_loan', models.CharField(max_length=128, null=True, verbose_name='贷款总额（%）')),
                ('non_interest_income', models.CharField(max_length=128, null=True, verbose_name='非利息收入（元）')),
                ('net_interest_margin', models.CharField(max_length=128, null=True, verbose_name='净息差(%)')),
            ],
            options={
                'db_table': 'yhzxinfofilled',
            },
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 6, 16, 17, 931326, tzinfo=utc)),
        ),
    ]
