# Generated by Django 2.0.2 on 2023-01-17 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0054_auto_20230117_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 10, 44, 38, 470690, tzinfo=utc)),
        ),
    ]
