# Generated by Django 2.0.2 on 2023-01-22 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0056_auto_20230122_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, null=True, verbose_name='表名')),
                ('col_1', models.CharField(max_length=128, null=True, verbose_name='属性1')),
                ('col_2', models.CharField(max_length=128, null=True, verbose_name='属性2')),
                ('col_3', models.CharField(max_length=128, null=True, verbose_name='属性3')),
                ('col_4', models.CharField(max_length=128, null=True, verbose_name='属性4')),
                ('col_5', models.CharField(max_length=128, null=True, verbose_name='属性5')),
                ('col_6', models.CharField(max_length=128, null=True, verbose_name='属性6')),
                ('col_7', models.CharField(max_length=128, null=True, verbose_name='属性7')),
                ('col_8', models.CharField(max_length=128, null=True, verbose_name='属性8')),
                ('col_9', models.CharField(max_length=128, null=True, verbose_name='属性9')),
                ('col_10', models.CharField(max_length=128, null=True, verbose_name='属性10')),
                ('col_11', models.CharField(max_length=128, null=True, verbose_name='属性11')),
                ('col_12', models.CharField(max_length=128, null=True, verbose_name='属性12')),
                ('col_13', models.CharField(max_length=128, null=True, verbose_name='属性13')),
                ('col_14', models.CharField(max_length=128, null=True, verbose_name='属性14')),
                ('col_15', models.CharField(max_length=128, null=True, verbose_name='属性15')),
                ('col_16', models.CharField(max_length=128, null=True, verbose_name='属性16')),
                ('col_17', models.CharField(max_length=128, null=True, verbose_name='属性17')),
                ('col_18', models.CharField(max_length=128, null=True, verbose_name='属性18')),
                ('col_19', models.CharField(max_length=128, null=True, verbose_name='属性19')),
                ('col_20', models.CharField(max_length=128, null=True, verbose_name='属性20')),
            ],
            options={
                'db_table': 'generalmaskinfo',
            },
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 8, 7, 4, 596195, tzinfo=utc)),
        ),
    ]
