# Generated by Django 2.0.2 on 2023-01-22 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0059_auto_20230122_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 11, 30, 50, 104210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='generaltableinfo',
            name='col_number',
            field=models.IntegerField(null=True, verbose_name='属性个数'),
        ),
    ]
