# Generated by Django 2.0.2 on 2022-10-26 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_auto_20211226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 3, 51, 38, 963251, tzinfo=utc)),
        ),
    ]
