# Generated by Django 2.0.2 on 2022-10-31 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_auto_20221031_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 10, 54, 53, 358181, tzinfo=utc)),
        ),
    ]
