# Generated by Django 2.0.2 on 2022-11-06 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_auto_20221105_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelConInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_name', models.CharField(max_length=128, null=True, verbose_name='删除属性')),
                ('del_status', models.CharField(max_length=128, null=True, verbose_name='布尔值')),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 3, 46, 7, 629250, tzinfo=utc)),
        ),
    ]
