# Generated by Django 2.0.2 on 2022-12-23 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0045_auto_20221220_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, null=True, verbose_name='模型名称')),
                ('model_G', models.CharField(max_length=128, null=True, verbose_name='生成器参数')),
                ('model_status', models.CharField(max_length=128, null=True, verbose_name='模型训练状态')),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 3, 15, 1, 920293, tzinfo=utc)),
        ),
    ]
