# Generated by Django 2.0.2 on 2022-12-23 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0046_auto_20221223_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfoFilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zcfz_id', models.CharField(max_length=128, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, null=True, verbose_name='公司名')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='类型')),
                ('bbd_url', models.CharField(max_length=128, null=True, verbose_name='数据来源')),
                ('bbd_type', models.CharField(max_length=128, null=True, verbose_name='数据类型')),
                ('cash_central_bank_funds', models.CharField(max_length=128, null=True, verbose_name='现金及存放中央银行款项(元)')),
                ('sellable_assetset', models.CharField(max_length=128, null=True, verbose_name='可供出售金融资产(元)')),
                ('risk_preparation', models.CharField(max_length=128, null=True, verbose_name='一般风险准备(元)')),
                ('interest_payable', models.CharField(max_length=128, null=True, verbose_name='应付利息(元)')),
                ('paid_in_capital', models.CharField(max_length=128, null=True, verbose_name='实收资本')),
                ('fixed_assets', models.CharField(max_length=128, null=True, verbose_name='固定资产')),
                ('total_assets', models.CharField(max_length=128, null=True, verbose_name='资产总计')),
                ('capital_reserves', models.CharField(max_length=128, null=True, verbose_name='资本公积')),
            ],
        ),
        migrations.CreateModel(
            name='FilledParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, null=True, verbose_name='表名')),
                ('rmse', models.CharField(max_length=128, null=True, verbose_name='误差值')),
                ('status', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 7, 22, 59, 197109, tzinfo=utc)),
        ),
    ]
