# Generated by Django 2.0.2 on 2023-01-11 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0048_auto_20221225_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 2, 55, 52, 256044, tzinfo=utc)),
        ),
    ]
