# Generated by Django 2.0.2 on 2023-01-17 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0050_auto_20230111_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_name', models.CharField(max_length=128, null=True, verbose_name='表名')),
                ('bz', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'parameterinfo',
            },
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 1, 52, 40, 415510, tzinfo=utc)),
        ),
    ]
