# Generated by Django 2.0.2 on 2023-01-17 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0052_auto_20230117_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 2, 0, 38, 451120, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='bankinfo',
            table='bankinfo',
        ),
        migrations.AlterModelTable(
            name='bankinfodelmark',
            table='bankinfodelmark',
        ),
        migrations.AlterModelTable(
            name='bankinfofilled',
            table='bankinfofilled',
        ),
        migrations.AlterModelTable(
            name='delconinfo',
            table='delconinfo',
        ),
        migrations.AlterModelTable(
            name='modelparameter',
            table='modelparameter',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
